TICKERS = [
    "AAPL", "MSFT", "NVDA", "GOOGL", "GOOG", "AMZN", "META", "TSLA", "AMD", "MU", "NOW","QQQ", "SPY",
]
MIN_DTE = 1
MAX_DTE = 7
SCAN_PUTS = True
SCAN_CALLS = True

PUT_TARGET_DELTA = -0.20
PUT_MIN_DELTA = -0.30
PUT_MAX_DELTA = -0.15
CALL_TARGET_DELTA = 0.20
CALL_MIN_DELTA = 0.15
CALL_MAX_DELTA = 0.30
MAX_BID_ASK_SPREAD_PCT = 0.10
EARNINGS_BUFFER_DAYS = 7
RV5_WEIGHT = 0.20
RV20_WEIGHT = 0.50
RV60_WEIGHT = 0.30
MIN_OPTION_BID = 0.05
TOP_N_EMAIL_RESULTS = 5
MIN_OPTION_VOLUME = 0
MIN_OPEN_INTEREST = 0
GEMINI_MODEL = "gemini-3.6-flash"
